version: '3.8'

volumes:
  s003-v9501_lele-da-app_temp:
    external: true
  s003-v9502_lele-da-app_config:
    external: true
  s003-v9503_lele-da-app_data:
    external: true
  s003-v9105_lele-da-db:
    external: true
  s003-v9599_lele-da-ts:
    external: true

networks:
  s003-n01_backend_general:
    external: true
  s003-n95_lele-da:
    external: true
  s003-n99_lele-da-ts:
    driver: bridge

services:
  s003-c9502_lele-da-front:
    container_name: s003-c9502_lele-da-front
    restart: unless-stopped
    volumes:
      - .:/workspace
    build:
      context: .
      dockerfile: Dockerfile.frontend

    env_file: .env
    ports:
      - "${FRONTEND_PORT}:8501"
      - "59555:5678"

    #working_dir: /workspace/002.04.02.04.01_DA-CodeFrontend
    #command: python -m debugpy --listen 0.0.0.0:5678 app/main.py

    #command: python -m debugpy --listen 0.0.0.0:5678 -m streamlit run app/main.py --server.address=0.0.0.0 --server.port=8501
    #network_mode: "service:s003-c9599_lele-da-ts"
    networks:
      - s003-n95_lele-da
